version: "2"

services:

  medusa:
    image: linuxserver/medusa
    container_name: medusa
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/pi/configs/medusa:/config
      - /mnt/samba/shared:/shared
    ports:
      - 8081:8081
    restart: unless-stopped

  deluge:
    image: ledokun/armhf-arch-delugevpn
    container_name: deluge
    cap_add:
      - NET_ADMIN
    ports:
      - 8112:8112
      - 8118:8118
      - 58846:58846
      - 58946:58946
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - UMASK=000
      - DEBUG=false
      - VPN_ENABLED=yes
      - VPN_USER=rota.giuseppe@gmail.com
      - VPN_PASS=dfashgfkjasdha1289377
      - VPN_PROV=custom
      - STRICT_PORT_FORWARD=yes
      - ENABLE_PRIVOXY=yes
      - LAN_NETWORK=192.168.0.0/24
      - NAME_SERVERS=103.86.96.100,103.86.99.100
      - DELUGE_DAEMON_LOG_LEVEL=info
      - DELUGE_WEB_LOG_LEVEL=info
    volumes:
      - /home/pi/configs/deluge_ledokun:/config
      - /mnt/samba/shared:/data
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/pi/configs/radarr:/config
#      - /mnt/samba/shared/kodi_videos/movies:/movies
#      - /mnt/samba/shared/downloaded:/downloads
      - /mnt/samba/shared:/data
    ports:
      - 7878:7878
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/pi/configs/jackett:/config
      - /mnt/samba/shared/monitored:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
 
#  heimdall:
#    image: linuxserver/heimdall
#    container_name: heimdall
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Europe/Madrid
#    volumes:
#      - /home/pi/configs/heimdall:/config
#    ports:
#      - 8083:80
#      - 8443:443
#    restart: unless-stopped
