version: "3"

services:

  medusa:
    image: linuxserver/medusa
    container_name: medusa
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - $HOME/configs/medusa:/config
      - $SHARED_PATH:/shared
    ports:
      - 8081:8081
    restart: unless-stopped
    dns:
      - 127.0.0.1
      - 1.1.1.1

  deluge:
    image: ledokun/armhf-arch-delugevpn
    container_name: deluge
    cap_add:
      - NET_ADMIN
    ports:
      - 8112:8112
      - 8118:8118
      - 58846:58846
      - 58946:58946
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - UMASK=000
      - DEBUG=false
      - VPN_ENABLED=yes
      - VPN_USER=rota.giuseppe@gmail.com
      - VPN_PASS=dfashgfkjasdha1289377
      - VPN_PROV=custom
      - STRICT_PORT_FORWARD=yes
      - ENABLE_PRIVOXY=yes
      - LAN_NETWORK=192.168.0.0/24
        #- NAME_SERVERS=103.86.96.100,103.86.99.100
      - NAME_SERVERS=1.1.1.1
      - DELUGE_DAEMON_LOG_LEVEL=info
      - DELUGE_WEB_LOG_LEVEL=info
    volumes:
      - $HOME/configs/deluge_ledokun:/config
      - $SHARED_PATH:/data
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

#  transmission:
#    image: haugene/transmission-openvpn:latest-armhf
#    cap_add:
#      - NET_ADMIN
#    devices:
#      - "/dev/net/tun"
#    restart: unless-stopped
#    ports:
#      - "9091:9091"
#      - "8888:8888"
#    dns:
#      - 8.8.8.8
#      - 8.8.4.4
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - $SHARED_PATH:/data
#      - $HOME/configs/transmission-openvpn:/config
#    environment:
#      - OPENVPN_PROVIDER=NORDVPN
#      - OPENVPN_USERNAME=rota.giuseppe@gmail.com
#      - OPENVPN_PASSWORD=dfashgfkjasdha1289377
#      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
#      - LOCAL_NETWORK=192.168.0.0/24 
#      - PUID=1000
#      - PGID=1000
#      - NORDVPN_COUNTRY=es
#      - NORDVPN_CATEGORY=legacy_p2p
#      - NORDVPN_PROTOCOL=udp
#      - LOG_TO_STDOUT=true

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - $HOME/configs/radarr:/config
      - $SHARED_PATH:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    dns:
      - 1.1.1.1

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - RUN_OPTS=-t -l
    volumes:
      - $HOME/configs/jackett:/config
      - $SHARED_PATH/monitored:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    dns:
      - 1.1.1.1

#  lazylibrarian:
#    image: linuxserver/lazylibrarian
#    container_name: lazylibrarian
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Europe/Madrid
#    volumes:
#      - $HOME/configs/lazylibrarian:/config
#      - $SHARED_PATH/books:/books
#    ports:
#      - 5299:5299
#    restart: unless-stopped

  pihole:
    image: pihole/pihole:latest
    environment:
      TZ: 'Europe/Madrid'
      WEBPASSWORD: ciccione
      ServerIP: 192.168.0.159
      #INTERFACE: eth0
      #WEB_PORT: 6080
      #IPv6: 'False'
    volumes:
      - $HOME/configs/pihole/etc/pihole:/etc/pihole/
      - $HOME/configs/pihole/etc/dnsmasq.d:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    network_mode: host
    restart: unless-stopped

# sonarr:
#   image: linuxserver/sonarr
#   container_name: sonarr
#   environment:
#     - PUID=1000
#     - PGID=1000
#     - TZ=Europe/Madrid
#   volumes:
#     - $HOME/configs/sonarr:/config
#     - $SHARED_PATH:/data
#   ports:
#     - 8989:8989
#   restart: unless-stopped
#   dns:
#     - 1.1.1.1
         
    #  heimdall:
    #    image: linuxserver/heimdall
    #    container_name: heimdall
    #    environment:
    #      - PUID=1000
    #      - PGID=1000
    #      - TZ=Europe/Madrid
    #    volumes:
    #      - $HOME/configs/heimdall:/config
    #    ports:
    #      - 8083:80
    #      - 8443:443
    #    restart: unless-stopped
