version: "3"

services:

  medusa:
    image: linuxserver/medusa
    container_name: medusa
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - $HOME/configs/medusa:/config
      - $SHARED_PATH:/shared
    ports:
      - 8081:8081
    restart: unless-stopped
    dns:
      - 127.0.0.1
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
       max-file: "2"
       max-size: "10m"
       mode: non-blocking

  deluge:
    image: ledokun/armhf-arch-delugevpn
    container_name: deluge
    cap_add:
      - NET_ADMIN
    ports:
      - 8112:8112
      - 8118:8118
      - 58846:58846
      - 58946:58946
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - UMASK=000
      - DEBUG=false
      - VPN_ENABLED=yes
      - VPN_USER=rota.giuseppe@gmail.com
      - VPN_PASS=3vvkes2x5rqn6
      - VPN_PROV=custom
      - STRICT_PORT_FORWARD=yes
      - ENABLE_PRIVOXY=yes
      - LAN_NETWORK=192.168.0.0/24
        #- NAME_SERVERS=103.86.96.100,103.86.99.100
      - NAME_SERVERS=1.1.1.1
      - DELUGE_DAEMON_LOG_LEVEL=info
      - DELUGE_WEB_LOG_LEVEL=info
    volumes:
      - $HOME/configs/deluge_ledokun:/config
      - $SHARED_PATH:/data
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
       max-file: "2"
       max-size: "10m"
       mode: non-blocking

#  transmission:
#    image: haugene/transmission-openvpn:latest-armhf
#    cap_add:
#      - NET_ADMIN
#    devices:
#      - "/dev/net/tun"
#    restart: unless-stopped
#    ports:
#      - "9091:9091"
#      - "8888:8888"
#    dns:
#      - 8.8.8.8
#      - 8.8.4.4
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - $SHARED_PATH:/data
#      - $HOME/configs/transmission-openvpn:/config
#    environment:
#      - OPENVPN_PROVIDER=NORDVPN
#      - OPENVPN_USERNAME=rota.giuseppe@gmail.com
#      - OPENVPN_PASSWORD=3vvkes2x5rqn6
#      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
#      - LOCAL_NETWORK=192.168.0.0/24 
#      - PUID=1000
#      - PGID=1000
#      - NORDVPN_COUNTRY=es
#      - NORDVPN_CATEGORY=legacy_p2p
#      - NORDVPN_PROTOCOL=udp
#      - LOG_TO_STDOUT=true

  radarr:
    image: linuxserver/radarr:arm32v7-version-v0.2.0.1504
    #image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - $HOME/configs/radarr:/config
      - $SHARED_PATH:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    dns:
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
       max-file: "2"
       max-size: "10m"
       mode: non-blocking

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - RUN_OPTS=-t -l
    volumes:
      - $HOME/configs/jackett:/config
      - $SHARED_PATH/monitored:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    dns:
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
       max-file: "2"
       max-size: "10m"
       mode: non-blocking
